### ISSUE TITLE
Theme missing acoustic and/or haptic feedback in buttons

### ISSUE THREAD

**Issue by williamborba** [peiffer-innovations/json_theme#126]
The normal is gestures should provide acoustic and/or haptic feedback.
Reference: https://api.flutter.dev/flutter/material/ButtonStyle/enableFeedback.html

My json_theme created in appainter.dev, its all righted, but, missing, sound touch, any tips?

**Comment by jpeiffer** [comment]
Didn't know about apppainter.dev, that thing is kind of cool and neat it uses this library.  That said... nope.  You can try putting in a breakpoint in the `decodeButtonStyle` to see if it's actually getting passed along as `true`.  But without any example app showing the issue, that's about the best I can do.
