### ISSUE TITLE
upgrading from older version creates error: 

### ISSUE THREAD

**Issue by AmirJV1** [peiffer-innovations/json_theme#139]
I have updated json_theme **from version 6.3.1 to version 6.4.0**
then, when building my apk, running: `flutter build apk` I'm getting this error
```This application cannot tree shake icons fonts. It has non-constant instances of IconData at the following locations:
  - file:///C:/Users/<myUser>/AppData/Local/Pub/Cache/hosted/pub.dev/json_theme-6.4.0/lib/src/codec/theme_decoder.dart:5473:16
Target aot_android_asset_bundle failed: Exception: Avoid non-constant invocations of IconData or try to build again with --no-tree-shake-icons.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command 'C:\Users\<myUser>\Documents\flutter\bin\flutter.bat'' finished with non-zero exit value 1
```

**Comment by jpeiffer** [comment]
The issue isn't here, it's that you need to pass in the `--no-tree-shake-icons` per the README.

> *Important Note*
> 
> Because this library allows for icons to be dynamically referenced, Flutter cannot tree shake icons because it has no way of knowing what icons may or may not be referenced. If you include this library, then you will need to add the --no-tree-shake-icons flag to your Flutter build or you will get an error stating that Flutter cannot tree shake the icons.
