### ISSUE TITLE
tree shake icon. unable to run build

### ISSUE THREAD

**Issue by 53huzefa-zeenwala** [peiffer-innovations/json_theme#140]
This application cannot tree shake icons fonts. It has non-constant instances of IconData at the following locations:
--
10:16:50.859 | - file:///vercel/.pub-cache/hosted/pub.dev/json_theme-6.3.2/lib/src/codec/theme_decoder.dart:5403:16
10:16:50.881 | Target web_release_bundle failed: Error: Avoid non-constant invocations of IconData or try to build again with --no-tree-shake-icons.

**Comment by eeoom** [comment]
same here

**Comment by hatch01** [comment]
same

**Comment by jpeiffer** [comment]
The issue isn't here, it's that you need to pass in the `--no-tree-shake-icons` per the README.

> *Important Note*
> 
> Because this library allows for icons to be dynamically referenced, Flutter cannot tree shake icons because it has no way of knowing what icons may or may not be referenced. If you include this library, then you will need to add the --no-tree-shake-icons flag to your Flutter build or you will get an error stating that Flutter cannot tree shake the icons.
