### ISSUE TITLE
Error after upgrading flutter version to 3.19.0

### ISSUE THREAD

**Issue by Ruslanbek0809** [peiffer-innovations/json_theme#160]
Getting this error after upgrading flutter version to 3.19.0 and dart version to 3.3.0: 
```
Error: The getter 'selectedRowColor' isn't defined for the class 'ThemeData'.
```

**Comment by jpeiffer** [comment]
Make sure you're using the latest version of this library as breaking changes happen due to the nature of it being tied so close to Flutter's code.  This particular attribute was removed a while ago so go ahead and upgrade and you should be fine.
