### ISSUE TITLE
version solving failed on master channel

### ISSUE THREAD

**Issue by flooo6297** [peiffer-innovations/json_theme#19]
When on the flutter master channel the Version solving fails, because json_schema and w_transport haven't been updated in a while.

    The current Dart SDK version is 2.12.0-76.0.dev.

    Because no versions of json_theme match >1.4.3+1 <2.0.0 and json_theme 1.4.3+1 depends on json_schema ^2.2.1, json_theme ^1.4.3+1 requires json_schema ^2.2.1.
    And because no versions of json_schema match >2.2.1 <3.0.0 and json_schema 2.2.1 depends on w_transport ^3.2.8, json_theme ^1.4.3+1 requires w_transport ^3.2.8.
    And because no versions of w_transport match >3.2.8 <4.0.0 and w_transport 3.2.8 depends on sockjs_client_wrapper ^1.0.5, json_theme ^1.4.3+1 requires sockjs_client_wrapper ^1.0.5.
    And because no versions of sockjs_client_wrapper match >1.0.14 <2.0.0 and sockjs_client_wrapper >=1.0.5 <1.0.14 depends on w_common ^1.9.0, json_theme ^1.4.3+1 requires w_common ^1.9.0 or sockjs_client_wrapper 1.0.14.
    So, because w_common >=0.2.0 <1.15.0 requires SDK version >=1.12.0 <2.0.0 and sockjs_client_wrapper 1.0.14 depends on w_common ^1.20.1, json_theme ^1.4.3+1 requires w_common ^1.15.0.

    Because no versions of w_common match >1.20.3 <2.0.0 and w_common >=1.15.0 <1.20.2 depends on intl >=0.14.0 <0.16.0, w_common >=1.15.0 <1.20.2-∞ or >1.20.3 <2.0.0 requires intl >=0.14.0 <0.16.0.
    And because w_common >=1.20.2 <1.20.3 depends on intl ^0.16.0 and w_common 1.20.3 depends on intl >=0.15.0 <0.17.0, w_common ^1.15.0 requires intl >=0.14.0 <0.17.0.
    And because json_theme ^1.4.3+1 requires w_common ^1.15.0 (1), json_theme ^1.4.3+1 requires intl >=0.14.0 <0.17.0.
    So, because quotes depends on both intl ^0.17.0-nullsafety.2 and json_theme ^1.4.3+1, version solving failed.
    pub get failed (1;     So, because quotes depends on both intl ^0.17.0-nullsafety.2 and json_theme ^1.4.3+1, version solving failed.)
    Process finished with exit code 1

Flutter doctor:

```Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 1.24.0-8.0.pre.374, on Microsoft Windows [Version 10.0.18363.1198], locale de-DE)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] IntelliJ IDEA Ultimate Edition (version 2020.2)
[√] VS Code (version 1.51.1)
[√] Proxy Configuration
[√] Connected device (4 available)

• No issues found!
```

**Comment by jpeiffer** [comment]
This may have been an issue with the master channel.  It resolves fine on the dev channel which is actually Flutter `1.25.0-8.0.pre` now.

Flutter doctor:
```
% flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 1.25.0-8.0.pre, on macOS 11.0.1 20B29 darwin-x64, locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] IntelliJ IDEA Community Edition (version 2020.1.2)
[✓] VS Code (version 1.52.0)
[✓] Connected device (7 available)

! Doctor found issues in 1 category.
```

flutter packages get
```
Running "flutter pub get" in json_theme...                         422ms
Running "flutter pub get" in example...                            487ms
```

That said, I am eventually planning on forking the `json_schema` dependency because as you said, it appears to have been abandoned.  It has other issues too like using git based dependencies rather than pub based ones which can cause CI/CD problems.

To track the need to replace that dependency, I opened a separate issue and am closing this one: https://github.com/peiffer-innovations/json_theme/issues/20
