### ISSUE TITLE
`dropdownMenuTheme` missing from Schema definition

### ISSUE THREAD

**Issue by vbrandl** [peiffer-innovations/json_theme#205]
We are using `json_theme` 6.5.0 with Flutter 3.22.3 and want to style a dropdown menu.

Therefore we set the following in our `theme.json`:

```json
  "dropdownMenuTheme": {
    "menuStyle": {
      "surfaceTintColor": "#ff9ecaff"
    }
  }
```

This works fine and the color is applied as expected but when schema validation is enabled in debug builds, this fails, because the `dropdownMenuTheme` key is missing from the schema definition under https://peiffer-innovations.github.io/flutter_json_schemas/schemas/json_theme/theme_data.json

We have to set `SchemaValidator.enabled = false;` to make this work.

**Comment by jpeiffer** [comment]
Thanks.  This was fixed today with 6.5.3.
