### ISSUE TITLE
The type 'AutovalidateMode' is not exhaustively 

### ISSUE THREAD

**Issue by lingyun000** [peiffer-innovations/json_theme#209]
DAET:3.5
FLUTTER:3.24

../../../../.pub-cache/hosted/pub.flutter-io.cn/json_theme-6.5.0+1/lib/src/codec/theme_encoder.dart:249:15: Error: The type 'AutovalidateMode' is not exhaustively matched by the switch cases since it doesn't match 'AutovalidateMode.onUnfocus'.
 - 'AutovalidateMode' is from 'package:flutter/src/widgets/form.dart' ('../../flutter/packages/flutter/lib/src/widgets/form.dart').
Try adding a default case or cases that match 'AutovalidateMode.onUnfocus'.
      switch (value) {
              ^
Target kernel_snapshot_program failed: Exception

Command PhaseScriptExecution failed with a nonzero exit code

**Comment by jpeiffer** [comment]
Merged but not yet deployed.  Seems 3.24 has a lot of depreciated stuff I need to remove before it will deploy.

**Comment by cyrilcolinet** [comment]
Hi back @jpeiffer thanks for the merge. I did a workaround in #216.
It just ignore the deprecation for now (since its not removed completely in latest flutter version).

Hope you're not too busy ;)

**Comment by jpeiffer** [comment]
Deployed tonight.
