### ISSUE TITLE
BottomNavigation schema contains invalid property - selectedIconColor

### ISSUE THREAD

**Issue by sebastian-softdev** [peiffer-innovations/json_theme#23]
## issue

When trying to set the property: selectedItemColor and error returns saying that property does not exist in the schema. There is a property call selectIconColor but that does not exists in the API: [flutter API](https://api.flutter.dev/flutter/material/BottomNavigationBarThemeData-class.html).

## solution
change selectedIconColor to selectedItemColor in order to allow updating that value for the bottom navigation bar

**Comment by jpeiffer** [comment]
Thanks for the issue and the contribution. A new version has been posted to fix this issue: 2.1.1.
