### ISSUE TITLE
timePickerTheme decoding

### ISSUE THREAD

**Issue by acx70** [peiffer-innovations/json_theme#29]
I am not sure if it's a problem but it took me a while to understand it. When in the Json you use "timePickerTheme" it does not work, if you use " "timePickerThemeData" it works.

Not working example:
``
{
...
  "timePickerTheme":  {
    "backgroundColor": "#ffffff"
  }
...
}
``

Working example:
``
{
...
  "timePickerThemeData":  {
    "backgroundColor": "#ffffff"
  }
...
}
``

**Comment by jpeiffer** [comment]
Should be fixed in 3.1.2+1.

**Comment by acx70** [comment]
It works with ^3.1.2+1
