### ISSUE TITLE
Allow using custom SystemUiOverlayStyle in theme.json

### ISSUE THREAD

**Issue by badsgahhl** [peiffer-innovations/json_theme#44]
## Problem

Currently in a theme.json you can only set appBarTheme:systemOverlayStyle to "light" or "dark". Nevertheless for more customization it would be great to set a fully SystemUiOverlayStyle there in the JSON and not just "light" or "dark".

Example:

```
{
  "$schema": "https://peiffer-innovations.github.io/flutter_json_schemas/schemas/json_theme/theme_data.json",
  "appBarTheme": {
    "backgroundColor": "transparent",
    "centerTitle": false,
    "systemOverlayStyle": {
      "statusBarColor": "#ffffdad4"
    }
  },
}
```

**Comment by jpeiffer** [comment]
Thanks for the suggestion.  This is available in 4.0.2.
