### ISSUE TITLE
Release build failing consistently when v 5.0.0 used

### ISSUE THREAD

**Issue by hicnar** [peiffer-innovations/json_theme#78]
Build failing on Linux and Mac machines with Flutter 3.7.0 stable
After reverting to 4.0.3+5 the build is back to green - please see the attached screenshot. 
(Note: flutter_2.0.5 is just a directory name, the version in use is as stated above)
![Screenshot 2023-01-26 at 00 22 33](https://user-images.githubusercontent.com/1816194/214724961-4b137734-a777-4c17-9b0b-c618d6da506b.png)

**Comment by jpeiffer** [comment]
This actually isn't an issue, it's by design.  This library allows icons to be dynamically referenced, which means Flutter cannot tree shake them.  You'll have to add the `--no-tree-shake-icons` flag to your build.

Updated the docs.
