### ISSUE TITLE
How can I use it in a freezed or json_serializable class?

### ISSUE THREAD

**Issue by MiniSuperDev** [peiffer-innovations/json_theme#92]
I want to use this package in classes from freezed or json_serializable, there is a built in way?
If not, how should be the code of a [JsonConverter](https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonConverter-class.html) that use your decoder/encoder, can you guide me please?

Thank you

**Comment by jpeiffer** [comment]
None of the above are supported by this package, and there's no intention to support them at this time.
